name: kend_rent_car
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  get_storage: ^2.0.3
  http: ^0.13.3
  splashscreen: ^1.3.5
  flutter_svg: ^0.19.3
  simple_animations: ^2.5.1
  page_transition: ^1.1.7+6
  intl: ^0.16.1
  image_picker: ^0.7.5
  http_parser: ^4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
    - assets/icons/
    - assets/

